### ISSUE TITLE
Sign of sine problem

### ISSUE THREAD

**Issue by bgpeyton** [jjgoings/pade#2]
Interestingly, `scipy.fftpack` predicts a negative sign for the three peaks of the discrete Fourier transform of the function `sin(2t) + sin(4t) + sin(8t)`. Currently the Padé code predicts positive signs. The reason for this is in lines 68 and 69 - `np.poly1d` contracts the `a` coefficients with the wrong-order phase terms (Eq. 29 of Bruner _et al_). `np.poly1d(np.flip(a))` and likewise for `b` fixes the issue. This also fixes imaginary-component sign issues with several other functions I've tested. 

_Why_ the sign of the peaks of the FT of a simple sum of sine functions would be negative is beyond me, and I'd like to understand it better. Another example of this is `sin(t) + cos(2t) + sin(3t) + cos(4t)`. You get alternating imaginary and real peaks at ω = {1,2,3,4}, as expected, but again the imaginary peaks (corresponding to the sine) are all negative. Padé also has a lot of difficulty with this example, even with damping.

**Comment by jjgoings** [comment]
Thanks. Indeed, the arguments passed to `np.poly1d()` were in the reverse order. I made your changes in 2606fc69. In the meantime, I've put up some tests. Even if I don't understand the sign of the sine yet, the fact that we agree with SciPy's `fft` implementation now is reassuring. 

Perhaps the difference is, as you mentioned elsewhere, phase shifting or incomplete sampling. I guess the FT of the sine is defined over -infty to infty, but here we are sampling from 0 to N. Maybe this has some impact.

Anyway, thanks @bgpeyton for pointing this out and suggesting the fix. I'll close for now and re-visit if I have any great ideas. Feel free to reach out / post here if you figure it out.
